<?php

namespace Database\Seeders;

use App\Models\Municipio;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class MunicipioSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $data = [
            ["nombre" => "Ahuachapán", "id_departamento" => 1],
            ["nombre" => "Apaneca", "id_departamento" => 1],
            ["nombre" => "Atiquizaya", "id_departamento" => 1],
            ["nombre" => "Concepción de Ataco", "id_departamento" => 1],
            ["nombre" => "El Refugio", "id_departamento" => 1],
            ["nombre" => "Guaymango", "id_departamento" => 1],
            ["nombre" => "Jujutla", "id_departamento" => 1],
            ["nombre" => "San Francisco Menéndez", "id_departamento" => 1],
            ["nombre" => "San Lorenzo", "id_departamento" => 1],
            ["nombre" => "San Pedro Puxtla", "id_departamento" => 1],
            ["nombre" => "Tacuba", "id_departamento" => 1],
            ["nombre" => "Turín", "id_departamento" => 1],
            [

                "nombre" => "Candelaria de la Frontera",
                "id_departamento" => 2,
            ],
            ["nombre" => "Chalchuapa", "id_departamento" => 2],
            ["nombre" => "Coatepeque", "id_departamento" => 2],
            ["nombre" => "El Congo", "id_departamento" => 2],
            ["nombre" => "El Porvenir", "id_departamento" => 2],
            ["nombre" => "Masahuat", "id_departamento" => 2],
            ["nombre" => "Metapán", "id_departamento" => 2],
            ["nombre" => "San Antonio Pajonal", "id_departamento" => 2],
            [

                "nombre" => "San Sebastián Salitrillo",
                "id_departamento" => 2,
            ],
            ["nombre" => "Santa Ana", "id_departamento" => 2],
            ["nombre" => "Santa Rosa Guachipilín", "id_departamento" => 2],
            ["nombre" => "Santiago de la Frontera", "id_departamento" => 2],
            ["nombre" => "Texistepeque", "id_departamento" => 2],
            ["nombre" => "Acajutla", "id_departamento" => 3],
            ["nombre" => "Armenia", "id_departamento" => 3],
            ["nombre" => "Caluco", "id_departamento" => 3],
            ["nombre" => "Cuisnahuat", "id_departamento" => 3],
            ["nombre" => "Izalco", "id_departamento" => 3],
            ["nombre" => "Juayúa", "id_departamento" => 3],
            ["nombre" => "Nahuizalco", "id_departamento" => 3],
            ["nombre" => "Nahulingo", "id_departamento" => 3],
            ["nombre" => "Salcoatitán", "id_departamento" => 3],
            ["nombre" => "San Antonio del Monte", "id_departamento" => 3],
            ["nombre" => "San Julián", "id_departamento" => 3],
            ["nombre" => "Santa Catarina Masahuat", "id_departamento" => 3],
            ["nombre" => "Santa Isabel Ishuatán", "id_departamento" => 3],
            ["nombre" => "Santo Domingo Guzmán", "id_departamento" => 3],
            ["nombre" => "Sonsonate", "id_departamento" => 3],
            ["nombre" => "Sonzacate", "id_departamento" => 3],
            ["nombre" => "Agua Caliente", "id_departamento" => 4],
            ["nombre" => "Arcatao", "id_departamento" => 4],
            ["nombre" => "Azacualpa", "id_departamento" => 4],
            ["nombre" => "Chalatenango (ciudad)", "id_departamento" => 4],
            ["nombre" => "Comalapa", "id_departamento" => 4],
            ["nombre" => "Citalá", "id_departamento" => 4],
            [

                "nombre" => "Concepción Quezaltepeque",
                "id_departamento" => 4,
            ],
            ["nombre" => "Dulce Nombre de María", "id_departamento" => 4],
            ["nombre" => "El Carrizal", "id_departamento" => 4],
            ["nombre" => "El Paraíso", "id_departamento" => 4],
            ["nombre" => "La Laguna", "id_departamento" => 4],
            ["nombre" => "La Palma", "id_departamento" => 4],
            ["nombre" => "La Reina", "id_departamento" => 4],
            ["nombre" => "Las Vueltas", "id_departamento" => 4],
            ["nombre" => "Nueva Concepción", "id_departamento" => 4],
            ["nombre" => "Nueva Trinidad", "id_departamento" => 4],
            ["nombre" => "Nombre de Jesús", "id_departamento" => 4],
            ["nombre" => "Ojos de Agua", "id_departamento" => 4],
            ["nombre" => "Potonico", "id_departamento" => 4],
            ["nombre" => "San Antonio de la Cruz", "id_departamento" => 4],
            ["nombre" => "San Antonio Los Ranchos", "id_departamento" => 4],
            ["nombre" => "San Fernando", "id_departamento" => 4],
            ["nombre" => "San Francisco Lempa", "id_departamento" => 4],
            ["nombre" => "San Francisco Morazán", "id_departamento" => 4],
            ["nombre" => "San Ignacio", "id_departamento" => 4],
            ["nombre" => "San Isidro Labrador", "id_departamento" => 4],
            ["nombre" => "San José Cancasque", "id_departamento" => 4],
            ["nombre" => "San José Las Flores", "id_departamento" => 4],
            ["nombre" => "San Luis del Carmen", "id_departamento" => 4],
            ["nombre" => "San Miguel de Mercedes", "id_departamento" => 4],
            ["nombre" => "San Rafael", "id_departamento" => 4],
            ["nombre" => "Santa Rita", "id_departamento" => 4],
            ["nombre" => "Tejutla", "id_departamento" => 4],
            ["nombre" => "Candelaria", "id_departamento" => 5],
            ["nombre" => "Cojutepeque", "id_departamento" => 5],
            ["nombre" => "El Carmen", "id_departamento" => 5],
            ["nombre" => "El Rosario", "id_departamento" => 5],
            ["nombre" => "Monte San Juan", "id_departamento" => 5],
            ["nombre" => "Oratorio de Concepción", "id_departamento" => 5],
            ["nombre" => "San Bartolomé Perulapía", "id_departamento" => 5],
            ["nombre" => "San Cristóbal", "id_departamento" => 5],
            ["nombre" => "San José Guayabal", "id_departamento" => 5],
            ["nombre" => "San Pedro Perulapán", "id_departamento" => 5],
            ["nombre" => "San Rafael Cedros", "id_departamento" => 5],
            ["nombre" => "San Ramón", "id_departamento" => 5],
            ["nombre" => "Santa Cruz Analquito", "id_departamento" => 5],
            ["nombre" => "Santa Cruz Michapa", "id_departamento" => 5],
            ["nombre" => "Suchitoto", "id_departamento" => 5],
            ["nombre" => "Tenancingo", "id_departamento" => 5],
            ["nombre" => "Aguilares", "id_departamento" => 6],
            ["nombre" => "Apopa", "id_departamento" => 6],
            ["nombre" => "Ayutuxtepeque", "id_departamento" => 6],
            ["nombre" => "Cuscatancingo", "id_departamento" => 6],
            ["nombre" => "Ciudad Delgado", "id_departamento" => 6],
            ["nombre" => "El Paisnal", "id_departamento" => 6],
            ["nombre" => "Guazapa", "id_departamento" => 6],
            ["nombre" => "Ilopango", "id_departamento" => 6],
            ["nombre" => "Mejicanos", "id_departamento" => 6],
            ["nombre" => "Nejapa", "id_departamento" => 6],
            ["nombre" => "Panchimalco", "id_departamento" => 6],
            ["nombre" => "Rosario de Mora", "id_departamento" => 6],
            ["nombre" => "San Marcos", "id_departamento" => 6],
            ["nombre" => "San Martín", "id_departamento" => 6],
            ["nombre" => "San Salvador", "id_departamento" => 6],
            ["nombre" => "Santiago Texacuangos", "id_departamento" => 6],
            ["nombre" => "Santo Tomás", "id_departamento" => 6],
            ["nombre" => "Soyapango", "id_departamento" => 6],
            ["nombre" => "Tonacatepeque", "id_departamento" => 6],
            ["nombre" => "Antiguo Cuscatlán", "id_departamento" => 7],
            ["nombre" => "Chiltiupán", "id_departamento" => 7],
            ["nombre" => "Ciudad Arce", "id_departamento" => 7],
            ["nombre" => "Colón", "id_departamento" => 7],
            ["nombre" => "Comasagua", "id_departamento" => 7],
            ["nombre" => "Huizúcar", "id_departamento" => 7],
            ["nombre" => "Jayaque", "id_departamento" => 7],
            ["nombre" => "Jicalapa", "id_departamento" => 7],
            ["nombre" => "La Libertad", "id_departamento" => 7],
            [

                "nombre" => "Nueva San Salvador (Santa Tecla)",
                "id_departamento" => 7,
            ],
            ["nombre" => "Nuevo Cuscatlán", "id_departamento" => 7],
            ["nombre" => "San Juan Opico", "id_departamento" => 7],
            ["nombre" => "Quezaltepeque", "id_departamento" => 7],
            ["nombre" => "Sacacoyo", "id_departamento" => 7],
            ["nombre" => "San José Villanueva", "id_departamento" => 7],
            ["nombre" => "San Matías", "id_departamento" => 7],
            ["nombre" => "San Pablo Tacachico", "id_departamento" => 7],
            ["nombre" => "Talnique", "id_departamento" => 7],
            ["nombre" => "Tamanique", "id_departamento" => 7],
            ["nombre" => "Teotepeque", "id_departamento" => 7],
            ["nombre" => "Tepecoyo", "id_departamento" => 7],
            ["nombre" => "Zaragoza", "id_departamento" => 7],
            ["nombre" => "Apastepeque", "id_departamento" => 8],
            ["nombre" => "Guadalupe", "id_departamento" => 8],
            ["nombre" => "San Cayetano Istepeque", "id_departamento" => 8],
            ["nombre" => "San Esteban Catarina", "id_departamento" => 8],
            ["nombre" => "San Ildefonso", "id_departamento" => 8],
            ["nombre" => "San Lorenzo", "id_departamento" => 8],
            ["nombre" => "San Sebastián", "id_departamento" => 8],
            ["nombre" => "San Vicente", "id_departamento" => 8],
            ["nombre" => "Santa Clara", "id_departamento" => 8],
            ["nombre" => "Santo Domingo", "id_departamento" => 8],
            ["nombre" => "Tecoluca", "id_departamento" => 8],
            ["nombre" => "Tepetitán", "id_departamento" => 8],
            ["nombre" => "Verapaz", "id_departamento" => 8],
            ["nombre" => "Cinquera", "id_departamento" => 9],
            ["nombre" => "Dolores", "id_departamento" => 9],
            ["nombre" => "Guacotecti", "id_departamento" => 9],
            ["nombre" => "Ilobasco", "id_departamento" => 9],
            ["nombre" => "Jutiapa", "id_departamento" => 9],
            ["nombre" => "San Isidro", "id_departamento" => 9],
            ["nombre" => "Sensuntepeque", "id_departamento" => 9],
            ["nombre" => "Tejutepeque", "id_departamento" => 9],
            ["nombre" => "Victoria", "id_departamento" => 9],
            ["nombre" => "Cuyultitán", "id_departamento" => 10],
            ["nombre" => "El Rosario", "id_departamento" => 10],
            ["nombre" => "Jerusalén", "id_departamento" => 10],
            ["nombre" => "Mercedes La Ceiba", "id_departamento" => 10],
            ["nombre" => "Olocuilta", "id_departamento" => 10],
            ["nombre" => "Paraíso de Osorio", "id_departamento" => 10],
            ["nombre" => "San Antonio Masahuat", "id_departamento" => 10],
            ["nombre" => "San Emigdio", "id_departamento" => 10],
            [

                "nombre" => "San Francisco Chinameca",
                "id_departamento" => 10,
            ],
            ["nombre" => "San Juan Nonualco", "id_departamento" => 10],
            ["nombre" => "San Juan Talpa", "id_departamento" => 10],
            ["nombre" => "San Juan Tepezontes", "id_departamento" => 10],
            ["nombre" => "San Luis Talpa", "id_departamento" => 10],
            ["nombre" => "San Luis La Herradura", "id_departamento" => 10],
            ["nombre" => "San Miguel Tepezontes", "id_departamento" => 10],
            ["nombre" => "San Pedro Masahuat", "id_departamento" => 10],
            ["nombre" => "San Pedro Nonualco", "id_departamento" => 10],
            ["nombre" => "San Rafael Obrajuelo", "id_departamento" => 10],
            ["nombre" => "Santa María Ostuma", "id_departamento" => 10],
            ["nombre" => "Santiago Nonualco", "id_departamento" => 10],
            ["nombre" => "Tapalhuaca", "id_departamento" => 10],
            ["nombre" => "Zacatecoluca", "id_departamento" => 10],
            ["nombre" => "Alegría", "id_departamento" => 11],
            ["nombre" => "Berlín", "id_departamento" => 11],
            ["nombre" => "California", "id_departamento" => 11],
            ["nombre" => "Concepción Batres", "id_departamento" => 11],
            ["nombre" => "El Triunfo", "id_departamento" => 11],
            ["nombre" => "Ereguayquín", "id_departamento" => 11],
            ["nombre" => "Estanzuelas", "id_departamento" => 11],
            ["nombre" => "Jiquilisco", "id_departamento" => 11],
            ["nombre" => "Jucuapa", "id_departamento" => 11],
            ["nombre" => "Jucuarán", "id_departamento" => 11],
            ["nombre" => "Mercedes Umaña", "id_departamento" => 11],
            ["nombre" => "Nueva Granada", "id_departamento" => 11],
            ["nombre" => "Ozatlán", "id_departamento" => 11],
            ["nombre" => "Puerto El Triunfo", "id_departamento" => 11],
            ["nombre" => "San Agustín", "id_departamento" => 11],
            ["nombre" => "San Buenaventura", "id_departamento" => 11],
            ["nombre" => "San Dionisio", "id_departamento" => 11],
            ["nombre" => "San Francisco Javier", "id_departamento" => 11],
            ["nombre" => "Santa Elena", "id_departamento" => 11],
            ["nombre" => "Santa María", "id_departamento" => 11],
            ["nombre" => "Santiago de María", "id_departamento" => 11],
            ["nombre" => "Tecapán", "id_departamento" => 11],
            ["nombre" => "Usulután", "id_departamento" => 11],
            ["nombre" => "Carolina", "id_departamento" => 12],
            ["nombre" => "Chapeltique", "id_departamento" => 12],
            ["nombre" => "Chinameca", "id_departamento" => 12],
            ["nombre" => "Chirilagua", "id_departamento" => 12],
            ["nombre" => "Ciudad Barrios", "id_departamento" => 12],
            ["nombre" => "Comacarán", "id_departamento" => 12],
            ["nombre" => "El Tránsito", "id_departamento" => 12],
            ["nombre" => "Lolotique", "id_departamento" => 12],
            ["nombre" => "Moncagua", "id_departamento" => 12],
            ["nombre" => "Nueva Guadalupe", "id_departamento" => 12],
            [

                "nombre" => "Nuevo Edén de San Juan",
                "id_departamento" => 12,
            ],
            ["nombre" => "Quelepa", "id_departamento" => 12],
            ["nombre" => "San Antonio del Mosco", "id_departamento" => 12],
            ["nombre" => "San Gerardo", "id_departamento" => 12],
            ["nombre" => "San Jorge", "id_departamento" => 12],
            ["nombre" => "San Luis de la Reina", "id_departamento" => 12],
            ["nombre" => "San Miguel", "id_departamento" => 12],
            ["nombre" => "San Rafael Oriente", "id_departamento" => 12],
            ["nombre" => "Sesori", "id_departamento" => 12],
            ["nombre" => "Uluazapa", "id_departamento" => 12],
            ["nombre" => "Arambala", "id_departamento" => 13],
            ["nombre" => "Cacaopera", "id_departamento" => 13],
            ["nombre" => "Chilanga", "id_departamento" => 13],
            ["nombre" => "Corinto", "id_departamento" => 13],
            [

                "nombre" => "Delicias de Concepción",
                "id_departamento" => 13,
            ],
            ["nombre" => "El Divisadero", "id_departamento" => 13],
            ["nombre" => "El Rosario", "id_departamento" => 13],
            ["nombre" => "Gualococti", "id_departamento" => 13],
            ["nombre" => "Guatajiagua", "id_departamento" => 13],
            ["nombre" => "Joateca", "id_departamento" => 13],
            ["nombre" => "Jocoaitique", "id_departamento" => 13],
            ["nombre" => "Jocoro", "id_departamento" => 13],
            ["nombre" => "Lolotiquillo", "id_departamento" => 13],
            ["nombre" => "Meanguera", "id_departamento" => 13],
            ["nombre" => "Osicala", "id_departamento" => 13],
            ["nombre" => "Perquín", "id_departamento" => 13],
            ["nombre" => "San Carlos", "id_departamento" => 13],
            ["nombre" => "San Fernando", "id_departamento" => 13],
            ["nombre" => "San Francisco Gotera", "id_departamento" => 13],
            ["nombre" => "San Isidro", "id_departamento" => 13],
            ["nombre" => "San Simón", "id_departamento" => 13],
            ["nombre" => "Sensembra", "id_departamento" => 13],
            ["nombre" => "Sociedad", "id_departamento" => 13],
            ["nombre" => "Torola", "id_departamento" => 13],
            ["nombre" => "Yamabal", "id_departamento" => 13],
            ["nombre" => "Yoloaiquín", "id_departamento" => 13],
            ["nombre" => "Anamorós", "id_departamento" => 14],
            ["nombre" => "Bolivar", "id_departamento" => 14],
            ["nombre" => "Concepción de Oriente", "id_departamento" => 14],
            ["nombre" => "Conchagua", "id_departamento" => 14],
            ["nombre" => "El Carmen", "id_departamento" => 14],
            ["nombre" => "El Sauce", "id_departamento" => 14],
            ["nombre" => "Intipucá", "id_departamento" => 14],
            ["nombre" => "La Unión", "id_departamento" => 14],
            ["nombre" => "Lislique", "id_departamento" => 14],
            ["nombre" => "Meanguera del Golfo", "id_departamento" => 14],
            ["nombre" => "Nueva Esparta", "id_departamento" => 14],
            ["nombre" => "Pasaquina", "id_departamento" => 14],
            ["nombre" => "Polorós", "id_departamento" => 14],
            ["nombre" => "San Alejo", "id_departamento" => 14],
            ["nombre" => "San José", "id_departamento" => 14],
            ["nombre" => "Santa Rosa de Lima", "id_departamento" => 14],
            ["nombre" => "Yayantique", "id_departamento" => 14],
            ["nombre" => "Yucuaiquín", "id_departamento" => 14],
        ];

        foreach ($data as $valor) {
            Municipio::create($valor);
        }
    }
}
