version: '3.2'

services:
  mariadb_laravel:
    restart: always
    image: docker.io/bitnami/mariadb:10.6
    # volumes:
    #   - ./backup:/bitnami/mariadb
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=user
      - MARIADB_DATABASE=api_rest
  api_rest_laravel:
    image: docker.io/bitnami/laravel:9
    ports:
      - 8100:8000
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mariadb_laravel
      - DB_PORT=3306
      - DB_USERNAME=user
      - DB_DATABASE=api_rest
      # - DB_HOST=postgis
      # - DB_PORT=5432
      # - DB_USERNAME=postgis
      # - DB_DATABASE=postgres
      # - DB_CONNECTION=pgsql
      # - DB_PASSWORD=postgis1234
    volumes:
      - ./api-rest:/app
    depends_on:
      - mariadb_laravel
      - postgis
    extra_hosts:
      - "host.docker.internal:host-gateway" 
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8110:80
    environment:
      - MYSQL_HOST=mysql
      - PMA_ARBITRARY=1
    depends_on:
      - mariadb_laravel
  postgis:
    image: postgis/postgis:13-3.3
    restart: always
    ports:
      - 8300:80
    environment:
      - POSTGRES_USER=postgis
      - POSTGRES_PASSWORD=postgis1234
      - POSTGRES_DB=postgis
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgis@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=postgis
    ports:
      - 8400:80
    depends_on:
      - postgis
  nginx:
    image: docker.io/bitnami/nginx:1.23
    ports:
      - 8443:443
    volumes:
      - ./block/:/opt/bitnami/nginx/conf/server_blocks/
      - ../certs:/certs
      # - ./api-rest:/app
    depends_on:
      - api_rest_laravel