version: "3.7"
volumes:
    postgres-data:
services:
    proxy:
        image: nginx:latest
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./:/var/www/app
            - ./docker/nginx/nginx-site-${SERVER_PROTOCOL:-http}.conf:/etc/nginx/conf.d/default.conf
            - ./docker/certs/bundle.crt:/etc/certs/bundle.crt
            - ./docker/certs/private.key:/etc/certs/private.key
        depends_on:
            - php

    php:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        image: laravelgis-php:latest
        ports:
            - 5173:5173
        volumes:
            - ./:/var/www/app
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        depends_on:
            - postgres

    postgres:
        image: postgis/postgis:15-3.3
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        environment:
            PGDATA: /var/lib/postgresql/data
            POSTGRES_DB: ${DB_DATABASE:-registrackerdb}
            POSTGRES_USER: ${DB_USERNAME:-registracker}
            POSTGRES_PASSWORD: ${DB_PASSWORD:-registracker#1234}

    pgadmin:
        image: dpage/pgadmin4:latest
        restart: always
        environment:
            - PGADMIN_DEFAULT_EMAIL=postgis@gmail.com
            - PGADMIN_DEFAULT_PASSWORD=postgis
        ports:
            - 8086:80
        volumes:
            - ./docker/pgadmin/servers.json:/pgadmin4/servers.json
        depends_on:
            - postgres
