<?php

namespace Database\Seeders;

use App\Models\Municipio;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class MunicipioSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $data = [
            ["id" => 1, "nombre" => "Ahuachapán", "id_departamento" => 1],
            ["id" => 2, "nombre" => "Apaneca", "id_departamento" => 1],
            ["id" => 3, "nombre" => "Atiquizaya", "id_departamento" => 1],
            ["id" => 4, "nombre" => "Concepción de Ataco", "id_departamento" => 1],
            ["id" => 5, "nombre" => "El Refugio", "id_departamento" => 1],
            ["id" => 6, "nombre" => "Guaymango", "id_departamento" => 1],
            ["id" => 7, "nombre" => "Jujutla", "id_departamento" => 1],
            ["id" => 8, "nombre" => "San Francisco Menéndez", "id_departamento" => 1],
            ["id" => 9, "nombre" => "San Lorenzo", "id_departamento" => 1],
            ["id" => 10, "nombre" => "San Pedro Puxtla", "id_departamento" => 1],
            ["id" => 11, "nombre" => "Tacuba", "id_departamento" => 1],
            ["id" => 12, "nombre" => "Turín", "id_departamento" => 1],
            [
                "id" => 13,
                "nombre" => "Candelaria de la Frontera",
                "id_departamento" => 2,
            ],
            ["id" => 14, "nombre" => "Chalchuapa", "id_departamento" => 2],
            ["id" => 15, "nombre" => "Coatepeque", "id_departamento" => 2],
            ["id" => 16, "nombre" => "El Congo", "id_departamento" => 2],
            ["id" => 17, "nombre" => "El Porvenir", "id_departamento" => 2],
            ["id" => 18, "nombre" => "Masahuat", "id_departamento" => 2],
            ["id" => 19, "nombre" => "Metapán", "id_departamento" => 2],
            ["id" => 20, "nombre" => "San Antonio Pajonal", "id_departamento" => 2],
            [
                "id" => 21,
                "nombre" => "San Sebastián Salitrillo",
                "id_departamento" => 2,
            ],
            ["id" => 22, "nombre" => "Santa Ana", "id_departamento" => 2],
            ["id" => 23, "nombre" => "Santa Rosa Guachipilín", "id_departamento" => 2],
            ["id" => 24, "nombre" => "Santiago de la Frontera", "id_departamento" => 2],
            ["id" => 25, "nombre" => "Texistepeque", "id_departamento" => 2],
            ["id" => 26, "nombre" => "Acajutla", "id_departamento" => 3],
            ["id" => 27, "nombre" => "Armenia", "id_departamento" => 3],
            ["id" => 28, "nombre" => "Caluco", "id_departamento" => 3],
            ["id" => 29, "nombre" => "Cuisnahuat", "id_departamento" => 3],
            ["id" => 30, "nombre" => "Izalco", "id_departamento" => 3],
            ["id" => 31, "nombre" => "Juayúa", "id_departamento" => 3],
            ["id" => 32, "nombre" => "Nahuizalco", "id_departamento" => 3],
            ["id" => 33, "nombre" => "Nahulingo", "id_departamento" => 3],
            ["id" => 34, "nombre" => "Salcoatitán", "id_departamento" => 3],
            ["id" => 35, "nombre" => "San Antonio del Monte", "id_departamento" => 3],
            ["id" => 36, "nombre" => "San Julián", "id_departamento" => 3],
            ["id" => 37, "nombre" => "Santa Catarina Masahuat", "id_departamento" => 3],
            ["id" => 38, "nombre" => "Santa Isabel Ishuatán", "id_departamento" => 3],
            ["id" => 39, "nombre" => "Santo Domingo Guzmán", "id_departamento" => 3],
            ["id" => 40, "nombre" => "Sonsonate", "id_departamento" => 3],
            ["id" => 41, "nombre" => "Sonzacate", "id_departamento" => 3],
            ["id" => 42, "nombre" => "Agua Caliente", "id_departamento" => 4],
            ["id" => 43, "nombre" => "Arcatao", "id_departamento" => 4],
            ["id" => 44, "nombre" => "Azacualpa", "id_departamento" => 4],
            ["id" => 45, "nombre" => "Chalatenango (ciudad)", "id_departamento" => 4],
            ["id" => 46, "nombre" => "Comalapa", "id_departamento" => 4],
            ["id" => 47, "nombre" => "Citalá", "id_departamento" => 4],
            [
                "id" => 48,
                "nombre" => "Concepción Quezaltepeque",
                "id_departamento" => 4,
            ],
            ["id" => 49, "nombre" => "Dulce Nombre de María", "id_departamento" => 4],
            ["id" => 50, "nombre" => "El Carrizal", "id_departamento" => 4],
            ["id" => 51, "nombre" => "El Paraíso", "id_departamento" => 4],
            ["id" => 52, "nombre" => "La Laguna", "id_departamento" => 4],
            ["id" => 53, "nombre" => "La Palma", "id_departamento" => 4],
            ["id" => 54, "nombre" => "La Reina", "id_departamento" => 4],
            ["id" => 55, "nombre" => "Las Vueltas", "id_departamento" => 4],
            ["id" => 56, "nombre" => "Nueva Concepción", "id_departamento" => 4],
            ["id" => 57, "nombre" => "Nueva Trinidad", "id_departamento" => 4],
            ["id" => 58, "nombre" => "Nombre de Jesús", "id_departamento" => 4],
            ["id" => 59, "nombre" => "Ojos de Agua", "id_departamento" => 4],
            ["id" => 60, "nombre" => "Potonico", "id_departamento" => 4],
            ["id" => 61, "nombre" => "San Antonio de la Cruz", "id_departamento" => 4],
            ["id" => 62, "nombre" => "San Antonio Los Ranchos", "id_departamento" => 4],
            ["id" => 63, "nombre" => "San Fernando", "id_departamento" => 4],
            ["id" => 64, "nombre" => "San Francisco Lempa", "id_departamento" => 4],
            ["id" => 65, "nombre" => "San Francisco Morazán", "id_departamento" => 4],
            ["id" => 66, "nombre" => "San Ignacio", "id_departamento" => 4],
            ["id" => 67, "nombre" => "San Isidro Labrador", "id_departamento" => 4],
            ["id" => 68, "nombre" => "San José Cancasque", "id_departamento" => 4],
            ["id" => 69, "nombre" => "San José Las Flores", "id_departamento" => 4],
            ["id" => 70, "nombre" => "San Luis del Carmen", "id_departamento" => 4],
            ["id" => 71, "nombre" => "San Miguel de Mercedes", "id_departamento" => 4],
            ["id" => 72, "nombre" => "San Rafael", "id_departamento" => 4],
            ["id" => 73, "nombre" => "Santa Rita", "id_departamento" => 4],
            ["id" => 74, "nombre" => "Tejutla", "id_departamento" => 4],
            ["id" => 75, "nombre" => "Candelaria", "id_departamento" => 5],
            ["id" => 76, "nombre" => "Cojutepeque", "id_departamento" => 5],
            ["id" => 77, "nombre" => "El Carmen", "id_departamento" => 5],
            ["id" => 78, "nombre" => "El Rosario", "id_departamento" => 5],
            ["id" => 79, "nombre" => "Monte San Juan", "id_departamento" => 5],
            ["id" => 80, "nombre" => "Oratorio de Concepción", "id_departamento" => 5],
            ["id" => 81, "nombre" => "San Bartolomé Perulapía", "id_departamento" => 5],
            ["id" => 82, "nombre" => "San Cristóbal", "id_departamento" => 5],
            ["id" => 83, "nombre" => "San José Guayabal", "id_departamento" => 5],
            ["id" => 84, "nombre" => "San Pedro Perulapán", "id_departamento" => 5],
            ["id" => 85, "nombre" => "San Rafael Cedros", "id_departamento" => 5],
            ["id" => 86, "nombre" => "San Ramón", "id_departamento" => 5],
            ["id" => 87, "nombre" => "Santa Cruz Analquito", "id_departamento" => 5],
            ["id" => 88, "nombre" => "Santa Cruz Michapa", "id_departamento" => 5],
            ["id" => 89, "nombre" => "Suchitoto", "id_departamento" => 5],
            ["id" => 90, "nombre" => "Tenancingo", "id_departamento" => 5],
            ["id" => 91, "nombre" => "Aguilares", "id_departamento" => 6],
            ["id" => 92, "nombre" => "Apopa", "id_departamento" => 6],
            ["id" => 93, "nombre" => "Ayutuxtepeque", "id_departamento" => 6],
            ["id" => 94, "nombre" => "Cuscatancingo", "id_departamento" => 6],
            ["id" => 95, "nombre" => "Ciudad Delgado", "id_departamento" => 6],
            ["id" => 96, "nombre" => "El Paisnal", "id_departamento" => 6],
            ["id" => 97, "nombre" => "Guazapa", "id_departamento" => 6],
            ["id" => 98, "nombre" => "Ilopango", "id_departamento" => 6],
            ["id" => 99, "nombre" => "Mejicanos", "id_departamento" => 6],
            ["id" => 100, "nombre" => "Nejapa", "id_departamento" => 6],
            ["id" => 101, "nombre" => "Panchimalco", "id_departamento" => 6],
            ["id" => 102, "nombre" => "Rosario de Mora", "id_departamento" => 6],
            ["id" => 103, "nombre" => "San Marcos", "id_departamento" => 6],
            ["id" => 104, "nombre" => "San Martín", "id_departamento" => 6],
            ["id" => 105, "nombre" => "San Salvador", "id_departamento" => 6],
            ["id" => 106, "nombre" => "Santiago Texacuangos", "id_departamento" => 6],
            ["id" => 107, "nombre" => "Santo Tomás", "id_departamento" => 6],
            ["id" => 108, "nombre" => "Soyapango", "id_departamento" => 6],
            ["id" => 109, "nombre" => "Tonacatepeque", "id_departamento" => 6],
            ["id" => 110, "nombre" => "Antiguo Cuscatlán", "id_departamento" => 7],
            ["id" => 111, "nombre" => "Chiltiupán", "id_departamento" => 7],
            ["id" => 112, "nombre" => "Ciudad Arce", "id_departamento" => 7],
            ["id" => 113, "nombre" => "Colón", "id_departamento" => 7],
            ["id" => 114, "nombre" => "Comasagua", "id_departamento" => 7],
            ["id" => 115, "nombre" => "Huizúcar", "id_departamento" => 7],
            ["id" => 116, "nombre" => "Jayaque", "id_departamento" => 7],
            ["id" => 117, "nombre" => "Jicalapa", "id_departamento" => 7],
            ["id" => 118, "nombre" => "La Libertad", "id_departamento" => 7],
            [
                "id" => 119,
                "nombre" => "Nueva San Salvador (Santa Tecla)",
                "id_departamento" => 7,
            ],
            ["id" => 120, "nombre" => "Nuevo Cuscatlán", "id_departamento" => 7],
            ["id" => 121, "nombre" => "San Juan Opico", "id_departamento" => 7],
            ["id" => 122, "nombre" => "Quezaltepeque", "id_departamento" => 7],
            ["id" => 123, "nombre" => "Sacacoyo", "id_departamento" => 7],
            ["id" => 124, "nombre" => "San José Villanueva", "id_departamento" => 7],
            ["id" => 125, "nombre" => "San Matías", "id_departamento" => 7],
            ["id" => 126, "nombre" => "San Pablo Tacachico", "id_departamento" => 7],
            ["id" => 127, "nombre" => "Talnique", "id_departamento" => 7],
            ["id" => 128, "nombre" => "Tamanique", "id_departamento" => 7],
            ["id" => 129, "nombre" => "Teotepeque", "id_departamento" => 7],
            ["id" => 130, "nombre" => "Tepecoyo", "id_departamento" => 7],
            ["id" => 131, "nombre" => "Zaragoza", "id_departamento" => 7],
            ["id" => 132, "nombre" => "Apastepeque", "id_departamento" => 8],
            ["id" => 133, "nombre" => "Guadalupe", "id_departamento" => 8],
            ["id" => 134, "nombre" => "San Cayetano Istepeque", "id_departamento" => 8],
            ["id" => 135, "nombre" => "San Esteban Catarina", "id_departamento" => 8],
            ["id" => 136, "nombre" => "San Ildefonso", "id_departamento" => 8],
            ["id" => 137, "nombre" => "San Lorenzo", "id_departamento" => 8],
            ["id" => 138, "nombre" => "San Sebastián", "id_departamento" => 8],
            ["id" => 139, "nombre" => "San Vicente", "id_departamento" => 8],
            ["id" => 140, "nombre" => "Santa Clara", "id_departamento" => 8],
            ["id" => 141, "nombre" => "Santo Domingo", "id_departamento" => 8],
            ["id" => 142, "nombre" => "Tecoluca", "id_departamento" => 8],
            ["id" => 143, "nombre" => "Tepetitán", "id_departamento" => 8],
            ["id" => 144, "nombre" => "Verapaz", "id_departamento" => 8],
            ["id" => 145, "nombre" => "Cinquera", "id_departamento" => 9],
            ["id" => 146, "nombre" => "Dolores", "id_departamento" => 9],
            ["id" => 147, "nombre" => "Guacotecti", "id_departamento" => 9],
            ["id" => 148, "nombre" => "Ilobasco", "id_departamento" => 9],
            ["id" => 149, "nombre" => "Jutiapa", "id_departamento" => 9],
            ["id" => 150, "nombre" => "San Isidro", "id_departamento" => 9],
            ["id" => 151, "nombre" => "Sensuntepeque", "id_departamento" => 9],
            ["id" => 152, "nombre" => "Tejutepeque", "id_departamento" => 9],
            ["id" => 153, "nombre" => "Victoria", "id_departamento" => 9],
            ["id" => 154, "nombre" => "Cuyultitán", "id_departamento" => 10],
            ["id" => 155, "nombre" => "El Rosario", "id_departamento" => 10],
            ["id" => 156, "nombre" => "Jerusalén", "id_departamento" => 10],
            ["id" => 157, "nombre" => "Mercedes La Ceiba", "id_departamento" => 10],
            ["id" => 158, "nombre" => "Olocuilta", "id_departamento" => 10],
            ["id" => 159, "nombre" => "Paraíso de Osorio", "id_departamento" => 10],
            ["id" => 160, "nombre" => "San Antonio Masahuat", "id_departamento" => 10],
            ["id" => 161, "nombre" => "San Emigdio", "id_departamento" => 10],
            [
                "id" => 162,
                "nombre" => "San Francisco Chinameca",
                "id_departamento" => 10,
            ],
            ["id" => 163, "nombre" => "San Juan Nonualco", "id_departamento" => 10],
            ["id" => 164, "nombre" => "San Juan Talpa", "id_departamento" => 10],
            ["id" => 165, "nombre" => "San Juan Tepezontes", "id_departamento" => 10],
            ["id" => 166, "nombre" => "San Luis Talpa", "id_departamento" => 10],
            ["id" => 167, "nombre" => "San Luis La Herradura", "id_departamento" => 10],
            ["id" => 168, "nombre" => "San Miguel Tepezontes", "id_departamento" => 10],
            ["id" => 169, "nombre" => "San Pedro Masahuat", "id_departamento" => 10],
            ["id" => 170, "nombre" => "San Pedro Nonualco", "id_departamento" => 10],
            ["id" => 171, "nombre" => "San Rafael Obrajuelo", "id_departamento" => 10],
            ["id" => 172, "nombre" => "Santa María Ostuma", "id_departamento" => 10],
            ["id" => 173, "nombre" => "Santiago Nonualco", "id_departamento" => 10],
            ["id" => 174, "nombre" => "Tapalhuaca", "id_departamento" => 10],
            ["id" => 175, "nombre" => "Zacatecoluca", "id_departamento" => 10],
            ["id" => 176, "nombre" => "Alegría", "id_departamento" => 11],
            ["id" => 177, "nombre" => "Berlín", "id_departamento" => 11],
            ["id" => 178, "nombre" => "California", "id_departamento" => 11],
            ["id" => 179, "nombre" => "Concepción Batres", "id_departamento" => 11],
            ["id" => 180, "nombre" => "El Triunfo", "id_departamento" => 11],
            ["id" => 181, "nombre" => "Ereguayquín", "id_departamento" => 11],
            ["id" => 182, "nombre" => "Estanzuelas", "id_departamento" => 11],
            ["id" => 183, "nombre" => "Jiquilisco", "id_departamento" => 11],
            ["id" => 184, "nombre" => "Jucuapa", "id_departamento" => 11],
            ["id" => 185, "nombre" => "Jucuarán", "id_departamento" => 11],
            ["id" => 186, "nombre" => "Mercedes Umaña", "id_departamento" => 11],
            ["id" => 187, "nombre" => "Nueva Granada", "id_departamento" => 11],
            ["id" => 188, "nombre" => "Ozatlán", "id_departamento" => 11],
            ["id" => 189, "nombre" => "Puerto El Triunfo", "id_departamento" => 11],
            ["id" => 190, "nombre" => "San Agustín", "id_departamento" => 11],
            ["id" => 191, "nombre" => "San Buenaventura", "id_departamento" => 11],
            ["id" => 192, "nombre" => "San Dionisio", "id_departamento" => 11],
            ["id" => 193, "nombre" => "San Francisco Javier", "id_departamento" => 11],
            ["id" => 194, "nombre" => "Santa Elena", "id_departamento" => 11],
            ["id" => 195, "nombre" => "Santa María", "id_departamento" => 11],
            ["id" => 196, "nombre" => "Santiago de María", "id_departamento" => 11],
            ["id" => 197, "nombre" => "Tecapán", "id_departamento" => 11],
            ["id" => 198, "nombre" => "Usulután", "id_departamento" => 11],
            ["id" => 199, "nombre" => "Carolina", "id_departamento" => 12],
            ["id" => 200, "nombre" => "Chapeltique", "id_departamento" => 12],
            ["id" => 201, "nombre" => "Chinameca", "id_departamento" => 12],
            ["id" => 202, "nombre" => "Chirilagua", "id_departamento" => 12],
            ["id" => 203, "nombre" => "Ciudad Barrios", "id_departamento" => 12],
            ["id" => 204, "nombre" => "Comacarán", "id_departamento" => 12],
            ["id" => 205, "nombre" => "El Tránsito", "id_departamento" => 12],
            ["id" => 206, "nombre" => "Lolotique", "id_departamento" => 12],
            ["id" => 207, "nombre" => "Moncagua", "id_departamento" => 12],
            ["id" => 208, "nombre" => "Nueva Guadalupe", "id_departamento" => 12],
            [
                "id" => 209,
                "nombre" => "Nuevo Edén de San Juan",
                "id_departamento" => 12,
            ],
            ["id" => 210, "nombre" => "Quelepa", "id_departamento" => 12],
            ["id" => 211, "nombre" => "San Antonio del Mosco", "id_departamento" => 12],
            ["id" => 212, "nombre" => "San Gerardo", "id_departamento" => 12],
            ["id" => 213, "nombre" => "San Jorge", "id_departamento" => 12],
            ["id" => 214, "nombre" => "San Luis de la Reina", "id_departamento" => 12],
            ["id" => 215, "nombre" => "San Miguel", "id_departamento" => 12],
            ["id" => 216, "nombre" => "San Rafael Oriente", "id_departamento" => 12],
            ["id" => 217, "nombre" => "Sesori", "id_departamento" => 12],
            ["id" => 218, "nombre" => "Uluazapa", "id_departamento" => 12],
            ["id" => 219, "nombre" => "Arambala", "id_departamento" => 13],
            ["id" => 220, "nombre" => "Cacaopera", "id_departamento" => 13],
            ["id" => 221, "nombre" => "Chilanga", "id_departamento" => 13],
            ["id" => 222, "nombre" => "Corinto", "id_departamento" => 13],
            [
                "id" => 223,
                "nombre" => "Delicias de Concepción",
                "id_departamento" => 13,
            ],
            ["id" => 224, "nombre" => "El Divisadero", "id_departamento" => 13],
            ["id" => 225, "nombre" => "El Rosario", "id_departamento" => 13],
            ["id" => 226, "nombre" => "Gualococti", "id_departamento" => 13],
            ["id" => 227, "nombre" => "Guatajiagua", "id_departamento" => 13],
            ["id" => 228, "nombre" => "Joateca", "id_departamento" => 13],
            ["id" => 229, "nombre" => "Jocoaitique", "id_departamento" => 13],
            ["id" => 230, "nombre" => "Jocoro", "id_departamento" => 13],
            ["id" => 231, "nombre" => "Lolotiquillo", "id_departamento" => 13],
            ["id" => 232, "nombre" => "Meanguera", "id_departamento" => 13],
            ["id" => 233, "nombre" => "Osicala", "id_departamento" => 13],
            ["id" => 234, "nombre" => "Perquín", "id_departamento" => 13],
            ["id" => 235, "nombre" => "San Carlos", "id_departamento" => 13],
            ["id" => 236, "nombre" => "San Fernando", "id_departamento" => 13],
            ["id" => 237, "nombre" => "San Francisco Gotera", "id_departamento" => 13],
            ["id" => 238, "nombre" => "San Isidro", "id_departamento" => 13],
            ["id" => 239, "nombre" => "San Simón", "id_departamento" => 13],
            ["id" => 240, "nombre" => "Sensembra", "id_departamento" => 13],
            ["id" => 241, "nombre" => "Sociedad", "id_departamento" => 13],
            ["id" => 242, "nombre" => "Torola", "id_departamento" => 13],
            ["id" => 243, "nombre" => "Yamabal", "id_departamento" => 13],
            ["id" => 244, "nombre" => "Yoloaiquín", "id_departamento" => 13],
            ["id" => 245, "nombre" => "Anamorós", "id_departamento" => 14],
            ["id" => 246, "nombre" => "Bolivar", "id_departamento" => 14],
            ["id" => 247, "nombre" => "Concepción de Oriente", "id_departamento" => 14],
            ["id" => 248, "nombre" => "Conchagua", "id_departamento" => 14],
            ["id" => 249, "nombre" => "El Carmen", "id_departamento" => 14],
            ["id" => 250, "nombre" => "El Sauce", "id_departamento" => 14],
            ["id" => 251, "nombre" => "Intipucá", "id_departamento" => 14],
            ["id" => 252, "nombre" => "La Unión", "id_departamento" => 14],
            ["id" => 253, "nombre" => "Lislique", "id_departamento" => 14],
            ["id" => 254, "nombre" => "Meanguera del Golfo", "id_departamento" => 14],
            ["id" => 255, "nombre" => "Nueva Esparta", "id_departamento" => 14],
            ["id" => 256, "nombre" => "Pasaquina", "id_departamento" => 14],
            ["id" => 257, "nombre" => "Polorós", "id_departamento" => 14],
            ["id" => 258, "nombre" => "San Alejo", "id_departamento" => 14],
            ["id" => 259, "nombre" => "San José", "id_departamento" => 14],
            ["id" => 260, "nombre" => "Santa Rosa de Lima", "id_departamento" => 14],
            ["id" => 261, "nombre" => "Yayantique", "id_departamento" => 14],
            ["id" => 262, "nombre" => "Yucuaiquín", "id_departamento" => 14],
        ];

        foreach ($data as $valor) {
            Municipio::create($valor);
        }

    }
}
